name: Decision Tree Workflow

on:
  push:
    branches:
      - feature/final_exam

jobs:
  run_decision_tree:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this line if you have a requirements.txt file
        pip install pytest  # Add this line to install pytest

    - name: Run Decision_Tree.py
      run: python Decision_Tree.py
