name: Hyperparameter Tuning

on:
  push:
    branches:
      - feature/assignment3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your actual requirements file
        # Add any other setup steps you need here

    - name: Run the script
      run: |
        python plot_digits_classification.py  # Replace the name of your Python script
        
        # Add a loop to run the script with different image sizes
        for image_size in 4 6 8
        do
            echo "Running with image size: ${image_size}x${image_size}"
            python plot_digits_classification.py --image-size ${image_size}  # Replace with the argument to pass image size
        done

    # Add a new step to print a message
    - name: Print completion message
      run: echo "Hyperparameter Tuning workflow completed successfully!"

# You can add more steps as needed for your workflow
