on:
  push:
    branches:
      - feature/final_exam  # Adjust to match your branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this line if you have a requirements.txt file
        pip install pytest  # Add this line to install pytest

    - name: Run tests
      run: |
        python -m pytest tests/  # Assuming your tests are in a directory named "tests"
        
    - name: Build Docker images
      run: |
        docker build -t dependency_image -f DependencyDockerfile .
        docker build -t final_image -f FinalDockerfile .
        
    - name: Push Docker images to Azure Container Registry
      run: |
        docker login <your-azure-container-registry-url> -u <your-azure-registry-username> -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        docker tag dependency_image:latest <your-azure-container-registry-url>/dependency_image:latest
        docker tag final_image:latest <your-azure-container-registry-url>/final_image:latest
        docker push <your-azure-container-registry-url>/dependency_image:latest
        docker push <your-azure-container-registry-url>/final_image:latest
